### ISSUE TITLE
Various problems and help wanted

### ISSUE THREAD

**Issue by flatmax** [sitepoint/debian-image-builder#25] opened 2017-07-04 23:38 UTC
Hey, nice project !

I am trying to build a debian stretch PV AMI image. I get the following error ...

$ ./debian-image-builder ec2 --arch amd64 --codename stretch \
>     --volume-type instance \
>     --filesystem ext4 --volume-size 5 --volume-inodes 5000000 \
>     --plugin plugins/standard-packages \
>     --plugin plugins/move-s3-path \
>     --timezone Australia/Sydney --locale en_AU --charmap UTF-8 \
>     --virt paravirtual --name-suffix "$(date +%Y%m%d%H%M)" \
>     --description "Debian stretch 5Gb, paravirtual, instance-store"
Paravirtual instances cannot be partitioned.

Any suggestions ?

thanks
Matt

**Comment by flatmax** [comment] 2017-07-05 04:52
ok - got something working ...

git clone https://github.com/sitepoint/debian-image-builder.git
cd debian-image-builder
sed -i "s/'python-support'//" tasks/ec2/04-install-euca2ools-deps

./debian-image-builder ec2 --arch amd64 --codename stretch \
    --volume-type ebs \
    --filesystem ext4 --volume-size 5 --volume-inodes 5000000 \
    --plugin plugins/admin-user --plugin plugins/standard-packages \
    --timezone Australia/Sydney --locale en_AU --charmap UTF-8 \
    --virt paravirtual --name-suffix "$(date +%Y%m%d%H%M)" \
    --description "Debian stretch 5Gb, paravirtual, instance-store"

Which builds, but fails in the following ways :
When running euca-register :
euca-register: error (InvalidAMIID.NotFound): The image id '[aki-xxxxxxxxx]' does not exist
When I drop the "--kernel aki-xxxxxxxxx" part it works.

I then try to login to my instance, after creating it with the new debian stretch AMI :
$ ssh admin@ipAddress

The command just hangs ... any idea what I am doing wrong ?

thanks
Matt

**Comment by flatmax** [comment] 2017-07-05 10:17
Hey again, I have forked and changed to pull stretch from the debian repos :+1: https://github.com/flatmax/debian-image-builder

However now having trouble with setting the correct EC2_PRIVATE_KEY and  EC2_CERT variables.
Are they meant to be file names ? If so then are the files pulled from "X.509 Certificates" on IAM ?
If not are the actual keys placed there ?

thanks
Matt

**Comment by flatmax** [comment] 2017-07-05 11:03
OK - I got it, use RSA keys and generate the certificate ?
openssl req -new -x509 -key id_rsa -out id_rsa.cer
Does that work ?

Matt

**Comment by boltronics** [comment] 2017-12-01 06:22
Hi @flatmax. Sorry for the slow response - I completely forgot to get back to this issue. In future, please open separate issues for each topic.

Regarding your first post, I'm going to need more to work on. There have been a number of improvements regarding Stretch support recently, so perhaps the latest Git code will help.

In your second post, please put the shell input/output in a code block for readability (triple back-ticks). Your example doesn't show you using an `--kernel aki-xxxxxxxx` argument. Perhaps you typed it incorrectly, or used one for a different region?

Thanks for pointing out the bug in the `euca2ools-deps task` in the `tasks/ec2/04-install-euca2ools-deps` plugin when run on stretch. I usually run debian-image-builder on a jessie host, but will be moving to build on a stretch host soon. Unfortunately I don't get as much time as I'd like to work on this.

You also tried to connect using an `admin` user account using the `admin-user` plugin. It looks like a bug I must have introduced in 03d53014c894a7d5456b7ca6edf451e303038df9 where we used to modify a custom sysvinit script for the initial setup on first boot. That's all since been replaced by `cloud-init`, but the plugin wasn't updated to change the `cloud-init` config to specify a different default user.

To answer the questions in your third post, `EC2_PRIVATE_KEY` needs to be set as a valid path to the private certificate file for your IAM user. eg. `/root/pk.pem`. `EC2_CERT` is the same, but for your IAM user public certificate. eg. `/root/cert.pem`  These certificates need to be generated yourself (AWS provides instructions on how to do this [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-up-ami-tools.html?icmpid=docs_iam_console#ami-tools-managing-certs)) and uploaded to your IAM account, which is convenient to do via the IAM user management web interface.

HTH.

**Comment by boltronics** [comment] 2018-03-02 07:11
As of https://github.com/sitepoint/debian-image-builder/pull/32 I can confirm that building Jessy and Stretch AMIs on a Stretch host works without issue. If you're still having trouble, please re-open this issue or create a new one.

**Closed as completed by boltronics** 2018-03-02 07:11 UTC
Labels: question
